### ISSUE TITLE
💡 It is possible to add users to a thread without pinging them

### ISSUE THREAD

**Issue by Tc-001** [MarcusOtter/discord-needle#107]
### Describe the improvement

It is possible to add a user to a specific thread without pinging them.

1. Create a message in a thread without mentioning a user
2. Edit the message to mention a user

This will add said user to the thread without them receiving a ping.

### Problems this improvement solves

Some people would want to be in all threads, while not receiving a ping each time a new one gets created (like `@core` team in astro)

**Comment by MarcusOtter** [comment]
Wow that's an amazing find, this will be very helpful for adding people without pinging them! I had no idea about this functionality. Hope Discord doesn't break it any time soon, it almost seems unintended 😄

We should keep this in mind for #52!

**Comment by MarcusOtter** [comment]
I'll close this for now as it's primarily applicable on the issue I linked. I updated that issue and added a comment about this there. Thanks again!
