### ISSUE TITLE
💡 On member ban, remove all threads from Needle to that user

### ISSUE THREAD

**Issue by c43721** [MarcusOtter/discord-needle#113]
### Describe the improvement

When a user gets banned from a server, we should remove all threads that Needle created that the user owns.

### Problems this improvement solves

Banning members does NOT delete their threads (for good reasons likely). But, you still get the thread created and it just sits there, taking space. 

If a server nears the maximum amount of active threads (1000) from a bot raid or scam, you then no longer can create threads. 

### Alternative solutions

Keep doing what we do, literally nothing.

**Comment by MarcusOtter** [comment]
Closing in favor of #68 since that will accomplish the same thing. When banning a person you get the option to delete their messages. If you do that, and the messages have threads on them, #68 will delete or archive them (depending on if the threads have other messages in them or not)
