### ISSUE TITLE
🐛  Doesn't respect channel's default archive duration

### ISSUE THREAD

**Issue by LekoArts** [MarcusOtter/discord-needle#115]
### Describe the bug

Hi!
Thanks for creating and hosting the bot, I really appreciate it!

I'm currently using the hosted version and the server I've added it to has the maximum boost level, so one can set the archive duration to 1 week.

In https://github.com/MarcusOtter/discord-needle/pull/34 I saw:

> to clamp the auto-archive duration to the maximum ACTUAL allowed value

I understand the reasoning for this at that time but I think it's a bug that the default duration that is selected for the channel is not evaluated first before falling back to the actual allowed value.

So I'm talking about this channel setting at the bottom:

![Bildschirmfoto 2022-03-21 um 10 11 25](https://user-images.githubusercontent.com/16143594/159232201-3cebd868-ce00-4ce8-8e61-ebc24df4c65c.png)

Right now Needle sets every thread to 1 week which is too long, I want to have it at 24 hours.

### Steps to reproduce the bug

1. Server with boosted levels to have more duration than 1 week
2. Set default duration to 24 hours in channel
3. Needle uses boosted options, not 24 hours

### Expected behavior

I expect the following:

- Use channel setting
- If channel setting is set to something that doesn't exist anymore (as server is not boosted anymore) fallback to current max value behavior

**Comment by MarcusOtter** [comment]
@LekoArts this is a bug with Discord, see the [FAQ](https://github.com/MarcusOtter/discord-needle/wiki/FAQ#why-is-my-auto-archive-duration-1-week-even-though-it-is-set-to-24-hours)

**Comment by MarcusOtter** [comment]
Actually I will re-open this and do some experimenting. It could be that Discord says the default auto-archive duration is `null` when it's unset, in which case we default to using `MAX` but the UI shows that the default is `24h`.

I don't want to rely on how things look in the UI vs what the value we are actually getting is, but we might have to do it anyways. It's a know bug, but thank you for pointing this out specifically which made me think about it some more:
> I understand the reasoning for this at that time but I think it's a bug that the default duration that is selected for the channel is not evaluated first before falling back to the actual allowed value.

**Comment by MarcusOtter** [comment]
This is the method that calculates the final auto-archive duration:
```ts
export function getSafeDefaultAutoArchiveDuration(channel: TextChannel | NewsChannel): ThreadAutoArchiveDuration {
	const archiveDuration = channel.defaultAutoArchiveDuration;
	if (!archiveDuration || archiveDuration === "MAX") return "MAX";

	const highest = getHighestAllowedArchiveDuration(channel);
	return archiveDuration > highest
		? highest
		: archiveDuration;
}
```

The only time this would elevate the auto-archive delay is if `archiveDuration` is falsy.

**Comment by LekoArts** [comment]
Hi, thanks for pointing to the FAQ. When I followed the steps there I "fixed" my issue. Didn't know that the wiki existed 😬 

I can also try on my end the API with newly created channels and check what one gets for the auto-archive duration. The code snippet you gave makes sense, I'd probably also have written it this way 😄 It would be unfortunate if Discord's API doesn't give back the value that is the default as an actual value.

**Comment by LekoArts** [comment]
Ok, so I've created my own bot for testing purposes and I logged out https://discord.js.org/#/docs/discord.js/stable/class/BaseGuildTextChannel via slash command.

On a newly created channel the response doesn't contain `defaultAutoArchiveDuration`. A channel where I switched the 24 hours to something else and back now contains `"defaultAutoArchiveDuration": 1440,`

**Comment by MarcusOtter** [comment]
>  doesn't contain `defaultAutoArchiveDuration`

As in, it's null/undefined? That would explain it then.

**Comment by LekoArts** [comment]
Yes, It’s `undefined`, so doesn’t exist in the API response.
