### ISSUE TITLE
💡 Don't mention when closing a thread

### ISSUE THREAD

**Issue by EnderPlays25** [MarcusOtter/discord-needle#188]
### Describe the improvement

Instead of mentioning someone when a thread is archived, put their name instead.

### Problems this improvement solves

This causes ghost pings you can't disable, which is extremely annoying.

**Comment by MarcusOtter** [comment]
The archive message can be configured with `/configure message key:SUCCESS_THREAD_ARCHIVE_IMMEDIATE` if you want to change it, but I hadn't thought about shadow pings. I don't think I've been getting them. How are you archiving a thread with Needle, without having the thread visible in your client? Doesn't the ping get immediately read by yourself as you have the thread open when you archive it?

**Comment by EnderPlays25** [comment]
I"m on mobile, whenever i close a thread, it locks and i have to manually unarchive it to get rid of ghost pings.
Also I'll change the archive message.

**Comment by MarcusOtter** [comment]
Weird, I'll investigate this and see if we can figure something out. Thanks for the suggestions :)
