### ISSUE TITLE
🐛 Writing in a thread after someone else updated title will update title again

### ISSUE THREAD

**Issue by philipaarseth** [MarcusOtter/discord-needle#196]
### Describe the bug

If you write in a thread someone else has updated the title with /title needle will update the title again.

![Screenshot 2022-06-17 at 12 21 55](https://user-images.githubusercontent.com/31098164/174280889-9a420b36-8034-4003-99d9-8e29233af0ca.jpg)

### Steps to reproduce the bug

Steps to reproduce
Member A creates thread by writing in channel
Needle auto-creates thread
Member A changes title with /title
Member B writes in thread

### Expected behavior

Needle shouldn't run update title again.

**Comment by MarcusOtter** [comment]
This is because Needle removes the 🆕 emoji, since someone replied. If you don't want that emoji, run `/configure emojis` and set it to false. I think this issue can be closed but let me know if I misunderstood :)

**Comment by philipaarseth** [comment]
Right, that seems like it should be an opt-in feature.

On another note, it is currently not very easy to find documentation on how the bot works. I wasn't even aware that there was a FAQ. On the website there are no mention of any documentation or FAQ, so I just assumed there was none.
