### ISSUE TITLE
🐛 BUG: Bot requires `overrideConfig` to exist

### ISSUE THREAD

**Issue by MarcusOtter** [MarcusOtter/discord-needle#20]
**Describe the bug**
When the bot is cloned from `main`, it does not compile because the user needs to create `overrideConfig.json` for it to compile. This is because the following line in `configHelpers.ts`:
```ts
import * as overrideConfig from "../overrideConfig.json";
```

**To Reproduce**
1. Clone the repo
2. Try to run `npm run start`
3. See error

**Expected behavior**
Does not error

**Comment by MarcusOtter** [comment]
The fix should be to either read the file with `fs` and then `await import` it (just like the commands) or alternatively find some way to make the import optional (if possible)

**Comment by rebelchris** [comment]
Is the issue not related to `overrideConfig` not existing? 😅
What should be the contents of this file? *(I don't have it when cloning the repo)

**Comment by MarcusOtter** [comment]
@rebelchris That is exactly the problem! 😄 This issue is that the bot shouldn't require it to exist since it's supposed to be used for developers so they can enter their API key without leaking it to a repo (since the file it in `.gitignore`)

**The easiest workaround** currently is to copy the contents from `config.json` and pasting them into a newly created file called `overrideConfig.json` which will make the bot compile and hopefully work. I'm not far from fixing this and many of the other open issues, I just really need to find a day or two to work on this project.

Let me know if you have any other issues with the bot, happy to help!
Also, check out the [`custom-config`](https://github.com/MarcusOtter/discord-needle/tree/custom-config) branch where most of the recent work has been happening. Some of the issues should already be fixed there (but I've forgotten how stable the branch is currently)

**Comment by rebelchris** [comment]
I actually fixed this in my version.

I went for a `.env` solution as I want to host if on a HAAS platform like railwayapp.
What I did was introduce a `.env` where you can store the token and channel id.

This will be pulled in the `getConfig` function, that way we don't even need the override file.

Happy to submit a PR if you want?
This way users can host this on cloud solutions without exposing keys.

**Comment by MarcusOtter** [comment]
Sorry, I totally forgot to reply to this!

The `.env` idea is not bad, I'll give it some thought! The original idea was to give full power to the developer to have a global "override" config that will override anything regardless of what the server settings are, but that may end up not being used.

Thanks for the idea and the feedback, I appreaciate it :)

**Comment by MarcusOtter** [comment]
@rebelchris Just implemented dotenv on the `custom-config` branch, works flawlessly and with has much less bloat than `overrideConfig`! Wanted to say thanks again :) ❤️

**Comment by rebelchris** [comment]
That's awesome!
Let me know if you need any other help somewhere, will try out the `custom-config` branch soon :)
