### ISSUE TITLE
💡 Auto-permitting thread author to write in it

### ISSUE THREAD

**Issue by Morb0** [MarcusOtter/discord-needle#214]
### Describe the improvement

It would be nice to have option to automatically give author of thread permissions to send messages to it. This allow for some moderations, when only permitted roles can talk in that thread with author.

### Problems this improvement solves

Solve some modation system cases.

### Alternative solutions

I even think it should not be an optional setting, as cases where you would like the author would not be able to write to thread created by him - does not exist?

**Comment by Morb0** [comment]
Oops

**Comment by MarcusOtter** [comment]
Doing some spring cleaning with the issues :) But yeah, Needle will not be changing any permissions for users. This can be configured in the server's settings (and I think they have this permission by default when creating a new server).
