### ISSUE TITLE
🐛 BUG: Cannot create threads in servers that lost boost levels

### ISSUE THREAD

**Issue by MarcusOtter** [MarcusOtter/discord-needle#23]
**Describe the bug**
Discord lets you set the default thread archive duration on certain Discord channels. The value you are able to set it to depends on the server's boost level. 

However, if a server's boost level was 1 or 2 and they set the thread archive duration to their max, and then the server's boost level decreases, the channel's thread archive duration does not revert to an allowed value (even though the UI thinks this is the case).

![image](https://user-images.githubusercontent.com/35617441/147938875-69c81eee-f00e-4914-8c24-562e45bd1299.png)

Since Needle uses this value to determine the thread's archive duration, it can throw an exception in this case:

![image](https://user-images.githubusercontent.com/35617441/147939450-f7fb6feb-4449-4227-bcb3-ed33ef6daa30.png)

**To Reproduce**
Very difficult unless you have a bunch of server boosts laying around.

1. Boost a server to a higher boost level
2. Set the thread archive duration for a channel to the highest possible value
3. Enable autothreading in that channel
4. Remove the boost from the server, making it drop a boost level
5. Post a message in the channel
6. See exception (nothing happens with the bot)

**Expected behavior**
A thread is created.

**Comment by MarcusOtter** [comment]
Thanks to @WebDevSimplified for finding this issue!

**Comment by c43721** [comment]
This could be a discord api bug, will ask in ddevs
