### ISSUE TITLE
🐛 ✅ Archive immediately (DEFAULT) Option is not working

### ISSUE THREAD

**Issue by obed-vazquez** [MarcusOtter/discord-needle#231]
### Describe the bug

The archive-behavior 
✅ Archive immediately (DEFAULT)

Is not working properly. It just won't archive the thread upon creation.

### Steps to reproduce the bug

1. Add the Needle bot
2. create a test channel
3. give full permissions to the Needle bot to the channel
4. activate/configure the bot in the channel with: `/configure auto-threading channel:#test enabled:True archive-behavior:✅ Archive immediately (DEFAULT)`
5. Send a message in the test channel
6. A Thread is created
7. Automatic archive over the thread is expected but just a button to manually archive is shown.

### Expected behavior

An automatic archive over the thread is expected but just a button to manually archive is shown.

**Comment by MarcusOtter** [comment]
This is the intended behavior
![image](https://user-images.githubusercontent.com/35617441/180337514-06b40f01-7da2-44bd-879f-304b11756ddd.png)
