### ISSUE TITLE
💡 add ability to post a form immediately after thread is created

### ISSUE THREAD

**Issue by ReenigneArcher** [MarcusOtter/discord-needle#244]
### Describe the improvement

I am using needle in support channels. It would be nice if I could present a form/questionnaire to the user automatically that asks them questions about their environment.

**Comment by MarcusOtter** [comment]
Hi, unfortunately this is not possible. Discord only allows modals to open as responses to interactions. An interaction is clicking a button or typing a slash command — sending a message is not included. We may do something like this in the future where users have to click a button to open a thread, which we would use a modal for. That feature request is tracked here: #205

**Comment by ReenigneArcher** [comment]
Okay, I'm not sure if I'm asking for the same feature as in that request. I'm unsure if they are asking to have that with threads that are created automatically or not.

Would it be possible to add a button to this message? Which would then open a modal
![image](https://user-images.githubusercontent.com/42013603/182737835-9a42d445-d929-4adb-bcd6-986dd7cdd83b.png)

**Comment by MarcusOtter** [comment]
Fair, I'll leave the issue opened to be considered in the future.

**Comment by ReenigneArcher** [comment]
I am closing this as I think it would be quite complex to implement what I was imagining (in a customizable way for each server). Partially due to limitations of discord (not being able to include select menus in modals, or text input boxes in views). I will work on implementing this into my custom bot. I think I can watch for the creation of a thread, then send an interaction with view to the thread.

Either way, thank you for this great bot. It has really improved the organization of my server!

**Comment by MarcusOtter** [comment]
I don't think making it customizable would be *too* hard. And the modal limitations are temporary, more components are planned. We can leave it closed for now but might revesit it in the future.

> I think I can watch for the creation of a thread, then send an interaction with view to the thread.

Creating a thread is not an interaction, so you cannot reply with modals to thread creation.
