### ISSUE TITLE
🐛 application did not respond

### ISSUE THREAD

**Issue by opiliteX** [MarcusOtter/discord-needle#262]
### Describe the bug

I (normal user) use Needle, then I type a command (`/title`) and it says `The application did not respond`
the command executes _very_ late (7-10 min)

### Steps to reproduce the bug

1. a unknown condition (maybe bad internet)
2. run command
3. observe

### Expected behavior

change the threads title

**Comment by MarcusOtter** [comment]
Hi @opiliteX, is there any chance the title was over 100 characters?

**Comment by MarcusOtter** [comment]
Cannot reproduce on my end with "hello" as title

**Comment by opiliteX** [comment]
> Hi @opiliteX, is there any chance the title was over 100 characters?

i think

**Comment by opiliteX** [comment]
but the answer (executing the command) always came, but late

**Comment by MarcusOtter** [comment]
Gotcha, this is a duplicate of #72, thanks for reporting :) Will be fixed in next version.
