### ISSUE TITLE
💡 Forum compatibility 

### ISSUE THREAD

**Issue by Madis0** [MarcusOtter/discord-needle#271]
### Describe the improvement

While the new forum threads don't really need the bot to create them, they could still use the bot to have an automatic first message on them and possibly manage the archival as well.

### Problems this improvement solves

The new forum threads don't seem to have a too-visible way to post thread guidelines/a form, so I'd want to use the bot for that. Surely there is the customizable info button, but that depends on whether the users will click it or not, I want something that is visible inside every thread.

### Alternative solutions

A separate new bot that could do it

**Comment by MarcusOtter** [comment]
Leaning towards having a separate bot for this, but will wait and see when forum drops if there's a case for Needle to have any forum support.

**Comment by MarcusOtter** [comment]
Forums are out now and I don't see Needle interacting with them in any meaningful way any time soon. Would be a nice separate bot that just sends a configurable message when a forum post is created :)
