### ISSUE TITLE
🐛 WebSocketGateway handleConnection bug and socket.io server types bug

### ISSUE THREAD

**Issue by car1ot** [MarcusOtter/discord-needle#279]
### Describe the bug

Hello.
I have an issue of WebSocketGateway.

I am using socket.io websocket server, following NestJS documentation.
I need to identify users by session token by passing session token to connection url (security reasons).
So I want to check session token in websocket server connection method and disconnect websockets with bad sessions.

There is a method in NestJS Gateway: handleConnection. This method triggers only when socket.io client send specific handshake message!!!. I want make handleConnection to trigger when client just connected without sending specific socket.io protocol messages! There are no way to make this in NestJS.

I tried to access server engine. At this point types bug appeared.
There is no way to access server.engine. It is undefined. Engine accessed by server.server.engine. But there are no type for this.

P.S. about handleConnection method, I think this is new feature request or something like this. It probably not a bug.

### Steps to reproduce the bug

```
@WebSocketGateway(3000)
export class AppGateway implements OnGatewayInit {
  constructor() {}

  @WebSocketServer()
  public readonly server: Server;

  afterInit() {
    this.server.engine // => undefined
    this.server.server.engine // => typescript error: "server" value does not exist on type Server
    (this.server as any).server.engine // engine exists!

    (this.server as any).server.engine.on('connection', () => {
      console.log('client enstablished connection!'); // it triggers when client connect!
    })
  }
}
```

### Expected behavior

First of all, `handleConnection` should trigger when client connected, instead of triggering on socket.io client event.
Also, `server.engine` is undefined. It is accessed by `server.server.engine`, but there are no types for `server.server`.

**Comment by car1ot** [comment]
> This issue seems completely unrelated to Needle, which is a Discord bot that creates threads. Maybe you meant to open this in socket.io or NestJS?

I open this issue in nest and this issue got closed by owner. He told to write in discord. But in discord no one resolve issues.

**Comment by MarcusOtter** [comment]
I'm not affiliated with that server or anyone in it, and I don't know NestJS

**Comment by car1ot** [comment]
> I'm not affiliated with that server or anyone in it, and I don't know NestJS

Sorry, this was wrong repository.

**Comment by MarcusOtter** [comment]
No worries, hope you'll find an answer to your question
