### ISSUE TITLE
🐛 Lock emoji not comming

### ISSUE THREAD

**Issue by Manik2375** [MarcusOtter/discord-needle#288]
### Describe the bug

After we lock the thread the lock emoji (:lock:) should come, it's coming but after 1-2 times it's giving tick mark emoji.

### Steps to reproduce the bug

1. Create a thread
2. Lock the thread
3. Send a message (to unlock it)
4. Again lock the thread. 
5. Try 1-2 times if the bug doesn't come. 

![image](https://user-images.githubusercontent.com/71554953/187927694-2fe82055-0703-4d3f-ad2b-f2d4d15ea5a8.png)

### Expected behavior

After locking the thread the lock emoji :lock: should come.

**Comment by MarcusOtter** [comment]
Thanks for confirming, I was able to reproduce this (on iOS at least)

**Comment by MarcusOtter** [comment]
Seems like it's working now when I tried it. However if the message has existed for longer than 2-4h it probably won't work, because of https://github.com/MarcusOtter/discord-needle/issues/326

Can move further discussion there if necessary
