### ISSUE TITLE
🐛 Title mixup across servers 

### ISSUE THREAD

**Issue by Madis0** [MarcusOtter/discord-needle#290]
### Describe the bug

A day ago I set a custom title for new threads in server 265487088349216769, channel 714133506472804354. 
Today I noticed the same title on server 859124104644788234, channel 888872895881838632 (which I also manage). Note that I have not set a custom title for that channel, the only thing I edited there post-v3 was  custom buttons.

Any ideas?

### Steps to reproduce the bug

1. Run `/auto-thread channel: (ID 714133506472804354) reply-message: Custom message 🔥`
2. I don't know, change other thread settings on the other server?

### Expected behavior

One server should not affect the other, even if I manage both

**Comment by MarcusOtter** [comment]
On face value this seems very weird as the bot will always use the guild ID and doesn't care about the person that invokes the command. Are you sure you didn't accidentally do it in the other server the other day? Can you reproduce it again if you change the title?

**Comment by Madis0** [comment]
Tried changing titles on both servers but no, cannot reproduce again. 
I really don't think I did change it accidentally, because I 

* kept the log of commands ran and therefore couldn't see it there
* used the popup where I entered the title phrase once
* the two servers use different languages, so setting the title on the second server would not even make sense

Maybe you have some debug logs you can check?

**Comment by MarcusOtter** [comment]
I don't store any logs right now, I can only check them in real-time as they happen. I've tried reproducing and looking in the code how something like this may occur but to me I can't see how this would happen. If anyone could reproduce this let me know how!

**Comment by MarcusOtter** [comment]
Aha! I can reproduce it, and it makes sense :) 

Basically, as soon as you open the "Custom title" modal, the bot waits for you to submit a modal and gives you 15 minutes to do so. But right now it doesn't check that the modal submit has to be in the same server. So if you open the "custom title" modal, close it, then go to another server and set a custom title there, it will apply that custom title in both servers. Thank you for reporting this! 🎉

**Comment by c43721** [comment]
@MarcusOtter Also assign this to me, I would like to solve this.

**Comment by MarcusOtter** [comment]
Any updates @c43721?

**Comment by MarcusOtter** [comment]
Fixed with https://github.com/MarcusOtter/discord-needle/commit/c42f31dd86e12baa075823948cfbe0c84bc41fc2
