### ISSUE TITLE
💡 Add possibility to add newlines in `/setting`

### ISSUE THREAD

**Issue by MarcusOtter** [MarcusOtter/discord-needle#292]
### Describe the improvement

Right now settings are shown with a one line text input field, which apparently does not allow new lines. And since I removed the `\n` way of adding new lines, it's no longer possible to have new lines in settings.

### Problems this improvement solves

Lets people use new lines in settings :)

### Alternative solutions

- Add back `\n` - not as intuitive as seeing the new line in front of you

**Comment by MarcusOtter** [comment]
An easy fix for this would be to make all setting modals use the multiline input field :)

**Comment by Lofty-Brambles** [comment]
Hey there, I'd like to work on this!
