### ISSUE TITLE
💡 Specify texts to trigger auto-thread

### ISSUE THREAD

**Issue by ADeeeee** [MarcusOtter/discord-needle#293]
### Describe the improvement

Allow moderators to setup customized texts which could trigger the auto-thread.

For instance:
Any texts which includes "Group up" in the channel.

### Problems this improvement solves

Preventing creating useless threads because of mistakes in channel, so that the moderators could announce the rules / format that everyone should follow it.

### Alternative solutions

/auto-thread trigger-keyword: (regex support)

**Comment by MarcusOtter** [comment]
I believe this is a duplicate of #93 :)
