### ISSUE TITLE
💡 Feature: Request / suggestion 

### ISSUE THREAD

**Issue by Dhmee** [MarcusOtter/discord-needle#3]
Hi , first thanks for the good and free code , I suggest to get benefit from Remove user from thread function by auto remove any user after x second from his last message in thread just to keep the channels field clean for our users , specially in big servers 

better if it is optional from discord but what to do , we always need a workaround with discord :(

![image](https://user-images.githubusercontent.com/31671759/131216588-2fb0d82e-276c-450c-945e-274bbd2eb4cb.png)

![image](https://user-images.githubusercontent.com/31671759/131216605-05f6e51a-ac98-4747-b69e-1336d6a7bfdb.png)

**Comment by MarcusOtter** [comment]
Thank you for the suggestion! I think this is a bit out of scope for this small bot currently, but I may be looking to make a bigger, more generic thread moderation bot in the future. I'm not sure I understand your use case, are you saying people should get kicked out of the thread after sending a message in it? Wouldn't that make it very hard for those users to see new messages in those threads?

**Comment by MarcusOtter** [comment]
No response, closing. Happy to re-open if the suggestion can be clarified a bit!
