### ISSUE TITLE
💡 Archive button customization

### ISSUE THREAD

**Issue by Madis0** [MarcusOtter/discord-needle#31]
**Is your request for improvement related to a problem? Please describe.**
The messages can be configured, but the archive button itself cannot be.

**Describe the solution you'd like**
A way to configure the archive button text, color, visibility.

**Describe alternatives you've considered**
Configuring only the text would help as well.

**Additional context**

**Comment by MarcusOtter** [comment]
Would love to do this. I'm wondering how we can make this as easy as possible for the user to customize. I'm thinking we could add two optional parameters to `/configure autothreading`: `button-type` and `button-text`, where `button-text` is just a custom string, and `button-type` can be `red`, `blue`, `grey`, `green` and `hidden`, matching the available types:

![image](https://user-images.githubusercontent.com/35617441/149639450-08139363-ead2-4f69-9933-c449a6eb3acd.png)
Source: https://discordjs.guide/interactions/buttons.html#updating-the-button-message

My only worry is that we will end up lots of parameters on that command in the future making it hard to use. But perhaps we can split the parameters into separate commands at that point :)

Any thoughts on this approach @Madis0? Thank you for the suggestion!

**Comment by Madis0** [comment]
> But perhaps we can split the parameters into separate commands at that point :)

- /configure autothreading channel:#channel enabled:True 
- /configure autothreading channel:#channel custom-message:Blabla
- /configure autothreading channel:#channel archive-button text:Blabla
- /configure autothreading channel:#channel archive-button enabled:True
- /configure autothreading channel:#channel archive-button color:red

I would suggest mostly reusing the existing structure, and _not_ expecting a `custom-message` during the creation, instead split it to a separate command.

**Comment by MarcusOtter** [comment]
Perhaps just providing a better default is fine for now? Thoughts @Madis0?
Something like this:
![image](https://user-images.githubusercontent.com/35617441/151913434-de22c383-e564-4e0b-ba4c-db4f5102c6d5.png)

**Comment by Madis0** [comment]
The archive button seems cleaner, but the commands button I'm not so sure about - what is the purpose of it?

**Comment by MarcusOtter** [comment]
It does the same as `/help`, shows the available commands (like `/title`, `/close`, etc) Perhaps "available commands" or "all commands" would be a better text for the button?

**Comment by Madis0** [comment]
Yeah, but for the user only /title is usable. So perhaps add a button `✏️ Edit title` instead? 

Once clicked, it would pre-fill the chatbox with "/title " (if that is possible).

**Comment by MarcusOtter** [comment]
We cannot control the users' clients unfortunately, so an edit title button would be difficult as we still need text input from them. I figured seeing what the bot can do with /help is good, we can maybe even customize the output of the /help command to only show commands available to them.

**Comment by MarcusOtter** [comment]
Also it's future-proof if/when we decide to add more commands :)

**Comment by Madis0** [comment]
Right. In that case - yes, do limit it to the commands user can actually use. And the button could be `[/] Commands` or `[/] Actions`.

**Comment by MarcusOtter** [comment]
Thanks for the feedback! I'll go with Commands to stay consistent with Discord's naming convention :)

![image](https://user-images.githubusercontent.com/35617441/151940835-6ff1c471-f26d-4135-b48a-e2688e36a91d.png)

I'll leave this issue open since they should probably still be configurable at some point, but making the default better has to be the first step 😄
