### ISSUE TITLE
💡 Remove "NEW" emojis from the commands added last update

### ISSUE THREAD

**Issue by MarcusOtter** [MarcusOtter/discord-needle#316]
### Describe the improvement

The commands are no longer 🆕 so that emoji should be removed from the command descriptions.

### Problems this improvement solves

More clear to the user what was recently added.

### Alternative solutions

Leaving them in - looks bad :)

**Comment by Lofty-Brambles** [comment]
Hi, I'd like to resolve this issue along with the other one I asked for in #292 - Seems like a small enough thing that I can do alongside it if it's ok!
