### ISSUE TITLE
💡 Add 1 sec slowmode option

### ISSUE THREAD

**Issue by MarcusOtter** [MarcusOtter/discord-needle#317]
### Describe the improvement

From MrAustin on Discord:
> or do 1 second slowmode
> because 5 seconds is annoying

### Problems this improvement solves

> it prevents spammers
> But people won't complain

### Alternative solutions

Letting people set a custom slowmode altogether. Not a very intuitive solution since you have to specify it in seconds, so to get 6h slowmode is they have to enter "21600". I prefer the way we have now with just a bunch of options.

**Comment by nchristopher** [comment]
We could also parse the duration into seconds, so typing `6h` converts to `21600` automatically.

**Comment by MarcusOtter** [comment]
We could, but I don't want to deal with 6h 3m 2s and or like "6 hours" or typos and stuff (plus we need to tell the user how the command works in an intuitive way, hard to do)

**Comment by nchristopher** [comment]
If only Discord had a duration type.
