### ISSUE TITLE
💡 Create a filter to create Threads

### ISSUE THREAD

**Issue by 110301J** [MarcusOtter/discord-needle#332]
### Describe the improvement

Hi, I would like to suggest adding a filter so that the bot only creates Threads on messages that start or contain messages with X Characters.

### Problems this improvement solves

That the bot creates threads on messages that do not require discussion or are of little relevance.

### Alternative solutions

I'm not sure :(

**Comment by MarcusOtter** [comment]
Duplicate of #93
