### ISSUE TITLE
🐛 $THREAD_MENTION & $THREAD_NAME

### ISSUE THREAD

**Issue by Swelloza** [MarcusOtter/discord-needle#346]
### Describe the bug

$THREAD_MENTION & $THREAD_NAME not working when submitted to custom reply message in thread (/autothread channel custom message command)

### Steps to reproduce the bug

1. run command to change thread reply message and set the reply to have $THREAD_MENTION & $THREAD_NAME 2. type in autothread channel 2. reply omits $THREAD_MENTION & $THREAD_NAME

### Expected behavior

 $THREAD_MENTION & $THREAD_NAME should show the name or the channel mention

**Comment by MarcusOtter** [comment]
Can reproduce it

**Comment by MarcusOtter** [comment]
Fixed with https://github.com/MarcusOtter/discord-needle/commit/f30124a25e40867752d575544fbf10fa4fef43f1
