### ISSUE TITLE
🐛 BUG: newlines not working from commands

### ISSUE THREAD

**Issue by mrfrase3** [MarcusOtter/discord-needle#37]
**Describe the bug**
When setting the  message copy via command, adding in \n to add a newline doesn't work, and the \n is just displayed in the text

**To Reproduce**
configure a message with \n for newlines in it

**Expected behavior**
The message used after running the command should display text on new lines.

**Comment by MarcusOtter** [comment]
Thank you for filing this issue! Parsing the string for `\\n` and replacing it with `\n` may be a viable strategy to allow newlines until Discord lets us use multiline strings natively in the UI. As stated in a [comment on another issue](https://github.com/MarcusOtter/discord-needle/issues/26#issuecomment-1010547496), it seems like this update will come in a few months.

**Comment by MarcusOtter** [comment]
I will say that [Form interactions](https://devsnek.notion.site/Modal-aka-Form-Interactions-e839b3dd8c214eb08f950764a8328e36) will make the editing experience SO much better for this. Good things coming eventually!
