### ISSUE TITLE
💡 Improvement: Change license to AGPL

### ISSUE THREAD

**Issue by MarcusOtter** [MarcusOtter/discord-needle#38]
**Is your request for improvement related to a problem? Please describe.**
From nchristopher#1079 on Discord:
> Wouldn't it be more appropriate for Needle to be licensed under the AGPL rather than the GPL? The AGPL is identical to the GPL, with the added clause that it applies over networks (eg. Discord bots).

> Currently, someone could fork Needle and host it, keeping their source private. Unless that was your intention, I think the AGPL would be a better choice.

I prefer that people keep the source code for Needle open when they make their own modifications, and in this case AGPL supports this better than GPL.

**Describe the solution you'd like**
Change to [AGPL-3.0](https://www.gnu.org/licenses/agpl-3.0.txt)

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.gnu.org/licenses/why-affero-gpl.html

This change will probably happen with v2.0.

**Comment by nchristopher** [comment]
This is a great change to make as soon as possible, as license changes require approval from past contributors. At the moment, that's just @jasikpark.

**Comment by jasikpark** [comment]
an ok from me 👍 agpl sounds like an improvement 😁

**Comment by nchristopher** [comment]
Another important decision to make is whether to have the "or later" clause in the license. The "or later" clause is recommended by the FSF (creators of the GPL). If a newer version of the GPL was released, users could (optionally) use it instead. There are pros and cons to both approaches.
