### ISSUE TITLE
💡 Making thread for only video, image, link posted.

### ISSUE THREAD

**Issue by LyraelEyrie** [MarcusOtter/discord-needle#392]
### Describe the improvement

Is it possible to create new settings that only allow the bot to create a thread if user post on the channel with at least an attachment like image, video, youtube link etc ?

That would be perfect for what I need for my server, I tried to combine with another bot that only allows user post images/videos on channel but those bot also detecting any other message that did not have an image/video and keep deleteing the message inside the thread..

**Comment by MarcusOtter** [comment]
Hi, this is not possible right now.

Duplicate of #93
