### ISSUE TITLE
💡 Improvement: Add some slash commands + automatic notify roles

### ISSUE THREAD

**Issue by jasikpark** [MarcusOtter/discord-needle#4]
- [x] add a `/title <title of the thread>` slash command that allows the user to update the thread title
- [ ] add a `/pin <message id | message link>` slash command that allows the user to pin a message to the thread
- [x] add a `/thanks-all-done` or `/archive` or `/close` or `/done` slash command that allows the initial creator of the thread can close the thread when they're done.
- [ ] allow setting a role like `@notify-ideas-and-suggestions` or `@notify-support` that by default the maintainers are opted-into but anyone can sign up for, which will be added to any thread that is started! 

Thinking about this more, to make it less spammy: maybe this should be a round-robin sorta scheduling thing 🤔 where people who have that role are randomly assigned to each thread?

**Comment by MarcusOtter** [comment]
I like these ideas a lot! The `pin` command makes sense to me, but it could be abused too. Maybe only the creator of the thread should be allowed to pin messages (and those with permissions, of course)?

By default, the creator of the thread can archive it, so I think it makes sense to allow them to do this. I'm starting to wonder if there's a way to make the user create a thread with the bot.... It would make it easier to let them name and archive the thread... Need to think about it some more.

The round-robin thing sounds like it could be a good feature as long as it's configurable!

**Comment by MarcusOtter** [comment]
User Nero#5172 from Discord had the idea of detecting certain keywords in messages and setting the title to some variation of those keywords by default, and then giving the user the option to change this title. For example, in Astro some keywords could be `Markdown`, `CSS`, `Vue`, `Svelte`, `Routing`, etc. Would make a better default title than `(Name) (Date)` I think!

**Comment by MarcusOtter** [comment]
Title command added with https://github.com/MarcusOtter/discord-needle/pull/12

**Comment by MarcusOtter** [comment]
Close command and button added with https://github.com/MarcusOtter/discord-needle/pull/15

**Comment by MarcusOtter** [comment]
Choosing to close this as the main two parts are done: /title and /close

I don't see any obvious uses for the pin message command since threads are so short-lived (I don't think users can normally pin messages in their threads anyways?).

The role thing is possible by overriding the thread message when setting up auto-threading. Making a round-robin thingy is not quite within the scope of this project right now :)
