### ISSUE TITLE
💡 Disable reply in channel if there is thread for message 

### ISSUE THREAD

**Issue by kerstvo** [MarcusOtter/discord-needle#416]
### Describe the improvement

Can Needle forbid to reply to message with thread? 
Or just copy reply message to thread and remove original message?

**Comment by MarcusOtter** [comment]
1. Not yet, see #93 
2. No, it's been discussed before (for example #10 and lots on Discord) but with this we would have to move the original message into the thread which is not really in scope for Needle.
