### ISSUE TITLE
💡 Improvement: Add MongoDB database support

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#42]
**Is your request for improvement related to a problem? Please describe.**
You can't host it on hosting without persist file system.

**Describe the solution you'd like**
Add support that you can use MongoDB database for saving configs.

**Describe alternatives you've considered**
Add support for remote MySQL database.

**Additional context**

**Comment by MarcusOtter** [comment]
Hello @ririko5834, see discussion #35 for why we are not doing this right now. You're more than welcome to discuss the database topic in there! I do not have any plans to implement a database right now but I'm open for discussion.

**Comment by MarcusOtter** [comment]
Also, forks are more than welcome to implement support for this!
