### ISSUE TITLE
💡 Auto-Archive threads after some time of inactivity 

### ISSUE THREAD

**Issue by PoisoningVeins** [MarcusOtter/discord-needle#435]
### Describe the improvement

Add a setting for auto-archive threads after a certain amount of time, like, 1 hour, 1 day, 2 days, ... 1 week

**Comment by MarcusOtter** [comment]
This exists within Discord:

![bild](https://github.com/MarcusOtter/discord-needle/assets/35617441/6568a4f4-c8ff-4d50-a1cc-d037c0ca2695)

See the FAQ for how to set it up: https://github.com/MarcusOtter/discord-needle/wiki/FAQ
