### ISSUE TITLE
💡 Add option to archive thread as moderator (lock thread)

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#44]
**Is your request for improvement related to a problem? Please describe.**
Users can re-open the thread when they send message.

**Describe the solution you'd like**
Add option to force archive the thread as moderator, that users can't reopen it.

**Describe alternatives you've considered**
Add button that will be usable just by staff that will Force archive the thread.

**Additional context**

**Comment by MarcusOtter** [comment]
Same reasoning as #43 here, I would prefer to not implement features that already exist in Discord.

**Comment by MarcusOtter** [comment]
As you mentioned yourself, we would have to add something like `include-lock-button` and `include-delete-button` to `/configure autothreading` and also turn those buttons slash commands `/lock` and `/delete`. This is more UI-clutter than I would like for a feature that is already implemented in Discord.

I will close this for the same reasons as in #43 

> I don't see this being added right now, but I'll mark it as "maybe later" so we can revisit it in the future. One big goal for me is to keep the complexity down in this project, and re-implementing discord's features is not on top of my list of features that I want to add. Sorry!

**Comment by ririko5834** [comment]
Dont close all issues

**Comment by MarcusOtter** [comment]
They were already closed from february as you can see @ririko5834. I have just changed the status from "Completed" to "Not planned" which is a feature GitHub added the other day, that makes it easier to visualize *why* an issue was closed. I have not closed any new issues I think, or maybe one, I can't remember.

**Comment by ririko5834** [comment]
Can you reopen it?

**Comment by MarcusOtter** [comment]
As stated previously, Needle will not implement features that already exist in Discord. If you want Discord to implement buttons/something that makes locking/archiving threads easier, that should be feedback to Discord themselves at https://feedback.discord.com
