### ISSUE TITLE
Channel -> Thread and Vice-Versa💡 

### ISSUE THREAD

**Issue by gklewis-ataxiagames** [MarcusOtter/discord-needle#451]
### Describe the improvement

Make a function that can take the history of an entire channel and rebuild it in a thread with usernames, timestamps, and all in order to replace the channel without loosing any of its history.

Likewise, the inverse would also be super useful.

Perhaps, this could even be a premium feature if you're wanting/needing additional incentives.

### Problems this improvement solves

Well, since Discord themselves hasn't run with this idea yet, it would definitely fill in their gap. I'm sure plenty of users would appreciate it if it's possible.

**Comment by MarcusOtter** [comment]
Hey, sorry for taking so long to get to this.

This is a bit out of scope for Needle, as I try to keep it as small of a bot as possible. Needle will only automatically create threads when new messages are posted in a channel. I can see something like this being useful, hope you can find something that works!
