### ISSUE TITLE
Discourse intgeration so every tread can be posted to Discourse as post

### ISSUE THREAD

**Issue by nihatdemir79** [MarcusOtter/discord-needle#477]
### Describe the improvement

Discourse intgeration so every tread can be posted to Discourse as post

### Problems this improvement solves

Problem I am solving because I have discourse forum and i would like to send important discord treads to discourse as post. so all platforms will be in sync

### Alternative solutions

none

**Comment by MarcusOtter** [comment]
That is not in scope for Needle, unfortunately. I suggest looking for "Discourse to Discord bridge" projects :)
