### ISSUE TITLE
💡 Allow Creating threads at a certain time and for certain days periodically

### ISSUE THREAD

**Issue by Lqnk4** [MarcusOtter/discord-needle#501]
### Describe the improvement

I'd like to create a thread automatically for some recurring event. 

The feature should allow automatically creating a thread at a certain time of day, for certain days of the week.
The thread could be titled with a customizable timestamp

Maybe also include a custom initial message in the thread 

### Problems this improvement solves

This issue solves the problem of creating threads for recurring events

**Comment by MarcusOtter** [comment]
@Lqnk4 Thanks for the suggestion. This seems out of scope for Needle, there are many message scheduling bots out there. If you set up auto-threading in a channel (with Needle) and then schedule a bot to make messages there, you can achive this.
