### ISSUE TITLE
💡 Bots can't be auto-threaded?

### ISSUE THREAD

**Issue by RillaDikted** [MarcusOtter/discord-needle#502]
### Describe the improvement

I'm trying to set up a custom on-boarding process where a new member joins, and MEE6 sends a message in a channel that is set to auto-thread.  But your bot isn't letting MEE6 post be auto-threaded.  Am I doing something wrong?  Is there a setting that you can add to allow bots to be auto-threaded?

### Problems this improvement solves

Better automation for server related tasks.

**Comment by MarcusOtter** [comment]
@RillaDikted Hi, yes please use the `include-bots` option of `/auto-thread`

**Comment by RillaDikted** [comment]
omg that's it!  thanks so much.  now i just need to figure out how to get my bot message to auto-ping the new member lol

**Comment by MarcusOtter** [comment]
The [FAQ](https://needle/faq) lists the message variables you can use :)
