### ISSUE TITLE
💡 Add thread owner placeholder

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#59]
Add THREAD_OWNER placeholder that you can use for custom messages. It's useful to ping thread owner to let him know that their thread was closed.

**Comment by MarcusOtter** [comment]
Another wonderful suggestion, thank you! 🚀

**Comment by MarcusOtter** [comment]
We should wait until #60 is fixed before working on this as that bug will probably require a rewrite of message variables
