### ISSUE TITLE
🐛 Initial message is sometimes empty

### ISSUE THREAD

**Issue by c43721** [MarcusOtter/discord-needle#60]
**Describe the bug**
Sometimes the bot will not send the correct opening message.
![image](https://user-images.githubusercontent.com/55610086/152425520-c5c9fd0f-f813-413d-8f1b-191513df6e62.png)

**Expected behavior**
For this to be created by $AUTHOR in $CHANNEL

**Details**
Happens in V2. No futher investigation was done.

**Additional context**
I have not debugged this and is something I saw while answering a question. View it here:
https://discord.com/channels/574028054238593024/938896754504499293/938896757176295544

**Comment by MarcusOtter** [comment]
Oh noes

**Comment by MarcusOtter** [comment]
Posting in the same channel as the thread linked above did work, so it's not all the time in specific channels or anything like that. It's probably something with message context. I'm hoping it's rare but I might've seen two cases where this happens so far.

**Comment by MarcusOtter** [comment]
This is a race condition!

![image](https://user-images.githubusercontent.com/35617441/152428781-112d8155-362b-4e50-9c74-3841167b9a6c.png)
![image](https://user-images.githubusercontent.com/35617441/152428813-bbd62cb9-768f-41cc-954e-71f013e3768a.png)
![image](https://user-images.githubusercontent.com/35617441/152428828-8ab6b6a3-d6c5-4a52-b4e7-038cf041e644.png)

**Comment by MarcusOtter** [comment]
I think I have something in mind to fix this, just need to find the time

**Comment by MarcusOtter** [comment]
`Yozora#7824` had more context on Discord, explaining that this will sometimes replace thread close message. I fear that it may be possible to send close messages from other servers too, if customized 😬 Bad bug, I need to tackle this on the weekend

**Comment by nchristopher** [comment]
This issue can be un-pinned.

**Comment by MarcusOtter** [comment]
I was going to when I merged to `stable` but FINE, we'll have it your way 😉
