### ISSUE TITLE
💡 Responses in embeds

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#67]
Add config option that responses from needle (SUCCESS_THREAD_CREATE, SUCCESS_THREAD_ARCHIVE_IMMEDIATE, SUCCESS_THREAD_ARCHIVE_SLOW and others) will be sent in embed messages.

The option if you want embed or not should be configurable there for every message. 

I have idea how messages in config.json file could be saved when it contains embed:
```
"messages": {
        "SUCCESS_THREAD_CREATE": {"embed": true, "description": "Thread automatically created by $USER in $CHANNEL.", "title": "Thread created", "colour": "#00FF00", "timestamp": true, "footer_text": "$BOT_USERNAME",  "footer_icon": "$BOT_AVATAR" }
    }
```
Also placeholders $BOT_USERNAME and $BOT_AVATAR should be added.

**Comment by MarcusOtter** [comment]
Making this configurable would be quite nice. I feel like for the sake of consistency, ALL of the messages from the bot should be either embedded or not embedded, but maybe that's just me.

**Comment by ririko5834** [comment]
When there will be setting just to enable or disable embeds, you can't set embed title per message then.

**Comment by nchristopher** [comment]
Personally, I don't think any messages should be embedded unless it's necessary (`/help`). Additionally, this requires the `EMBED_LINKS` permission, so error handling would have to be implemented.

**Comment by c43721** [comment]
@nchristopher As long as we make it so Needle is invited with that, I don't see it being an issue. 

Though I think embeds are very nice, with how the current bot is designed, this would look a bit odd as we have 1 sentence long replies. 

Help command should certainly be an embed. That I can agree. Others? Stay the same. That's my opinion.

**Comment by MarcusOtter** [comment]
Agreed! Thank you for the input @nchristopher @c43721

**Comment by ririko5834** [comment]
Add maybe later label here
