### ISSUE TITLE
💡 Archive or delete threads automatically when users delete original message

### ISSUE THREAD

**Issue by MarcusOtter** [MarcusOtter/discord-needle#68]
**Is your request for improvement related to a problem? Please describe.**
From Muhymin#6005 on Discord:
> Some people ask questions in the support channel and then remove the original message. Is it possible to delete the thread automatically as the user removes his original message??

**Describe the solution you'd like**
When the parent message is deleted (by any means, banning user included):

If (the thread has no messages from anyone except for the bot AND the bot has the permissions to delete the thread): delete the thread.

If (the thread has messages OR the bot does not have permissions to delete the thread): archive the thread

**Describe alternatives you've considered**
N/A

**Additional context**
Perhaps this means that we don't need the code we implemented for #49, and instead we can solve #26

**Comment by c43721** [comment]
wow I didn't see this

**Comment by MarcusOtter** [comment]
Some users have said they would like this to be configurable

When message deleted options:
- Delete thread if empty, archive if not (DEFAULT)
- Always archive
- Always delete

**Comment by MarcusOtter** [comment]
Fun fact: This is exactly how Discord chose to implement forums. If a user tries to delete their post, they are allowed to do so (unlike threads), but only if there are no responses from users. If there are responses, they are only allowed to delete their original message.

![image](https://user-images.githubusercontent.com/35617441/183774912-d08282ff-24b5-4e64-a5f1-a0519590d5e4.png)

**Comment by mnkrome** [comment]
Oh, glad its already suggested. It would be amazing if implemented.
