### ISSUE TITLE
💡 Lock the thread as moderator

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#69]
When a member with MANAGE_THREADS clicks on the archive button, lock (force archive) the thread immediately. When thread owner (normal users) clicks on it, just archive the thread (that user can reopen it by writing message).

Command /close should work the same.

This option should be customisable in config file. Can be called `staffLockThread: true/false`

**Comment by ririko5834** [comment]
Maybe there should be option Lock thread in archive-behavior and archive-behavior-staff (this option should be added)

**Comment by MarcusOtter** [comment]
In my opinion this is added complexity for very little gain, and I'm not a big fan of having one button do two different things. I understand that it may be *slightly* more convenient to lock the thread with that button if you always want to lock the threads, but two button clicks (using Discord's UI) is not that bad. This also falls under not implementing what Discord already has a bit. I'm open for discussion as always, but I will close this for now.

**Comment by ririko5834** [comment]
Sad, I think that this is better than having more buttons.

**Comment by ririko5834** [comment]
When https://github.com/MarcusOtter/discord-needle/issues/70 can be implemented I dont see problem with adding this action too to `archive-behavior`
