### ISSUE TITLE
💡 Add config option to set if thread should be archived immediately or not when staff uses the command

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#70]
Add config option if you want to archive thread immediately when user who is staff clicked on button or used command or if you want just to change archive duration to 60 mins.

Currently, when staff uses /close, the thread is immediately archived. 

This option should be customisable in config file. Can be called `staffImmdediateArchiveThread: true/false`

**Comment by MarcusOtter** [comment]
This is already customizeable with `archive-behavior` under `/configure auto-threading`. Or do you mean that it would be a different archive behavior depending on if you are staff or not?

**Comment by ririko5834** [comment]
> Or do you mean that it would be a different archive behavior depending on if you are staff or not?

Yes

**Comment by ririko5834** [comment]
When this new option is enabled staffImmdediateArchiveThread: true
- staff clicks on button - thread is archived immediately
- user clicks on button - thread is archived in 1 hour

When this new option is disabled staffImmdediateArchiveThread: false
- staff clicks on button - thread is archived in 1 hour
- user clicks on button - thread is archived in 1 hour

**Comment by ririko5834** [comment]
There should be option what should happen when staff closes the thread too

**Comment by nchristopher** [comment]
It might be better to add an `immediate` option to `/close` that's only accessible to certain members.

**Comment by ririko5834** [comment]
That can be added too, but it should be customisable what should the bot do by default when user is staff and when there is normal user.

**Comment by ririko5834** [comment]
#69 Lock as moderator option should be added there too.

And then for /close there could be optional option with choices (archive in 1 hour, archive immediately, lock as moderator) to do different action rather than the default set action.

**Comment by MarcusOtter** [comment]
Not planned
