### ISSUE TITLE
💡 Better issue reporting

### ISSUE THREAD

**Issue by nchristopher** [MarcusOtter/discord-needle#73]
- [x] Create [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) for easier creation of issues.
- [ ] Create [project board(s)](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects) for tracking the status of issues.
- [ ] Create [milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) to track what needs to be done for new releases.
- [x] Remove the prefix (`BUG:` and `Improvement:`) from issue titles to reduce visual noise. The emoji & label should be enough.

Additionally, some opened issues are more subjective in nature. We should utilize [discussions](https://github.com/MarcusOtter/discord-needle/discussions) more often for this.

**Comment by c43721** [comment]
Probably copy what DJS has. I think their Github is a fantastic demonstration of how to use Github effectively for reviews, tracking statuses, and keeping in line with milestones.

**Comment by MarcusOtter** [comment]
I did try to maintain a project board earlier (https://github.com/users/MarcusOtter/projects/2) but I really don't find myself keeping it up to date, especially since the goals for each "release" aren't well defined enough.

**Comment by MarcusOtter** [comment]
I'd like to check out code owners a bit more though before I'm closing this issue :)

**Comment by nchristopher** [comment]
In my opinion, code owners wouldn't be very useful currently, as none of the contributors have a specific set of things they work on.

**Comment by MarcusOtter** [comment]
Had a quick glance and yeah, doesn't seem super useful right now. I'll close this issue as I'm not particularly excited about using project boards or milestones right now.
