### ISSUE TITLE
🐛 Cannot invite bot, not verified

### ISSUE THREAD

**Issue by MarcusOtter** [MarcusOtter/discord-needle#79]
### Describe the bug

Heads up new users: you will not be able to add Needle to a server before Discord goes through my verification request.
I sent my request one day after Discord gave me the chance (when we hit 76 servers, which is 7 days ago at the time of writing), but since they're behind on looking through requests it may take a while before new servers can add Needle.
I have no ETA on this but some users have reported up to a month for verification requests to go through :/
Nothing I can do about this unfortunately, the ball is in their court

![image](https://user-images.githubusercontent.com/35617441/153063709-30bb55af-58dc-4783-a430-dcf3abef6846.png)

### Steps to reproduce the bug

N/A

### Expected behavior

N/A

**Comment by NicolasQuenon** [comment]
Hello ! Same problem for me, do you have a solution ? 
Thanks

**Comment by MarcusOtter** [comment]
No solution available yet, still waiting for Discord.

**Comment by MarcusOtter** [comment]
Finally verified!
