### ISSUE TITLE
💡 Improvement: update title based on every message

### ISSUE THREAD

**Issue by FredKSchott** [MarcusOtter/discord-needle#8]
I'd love if we could create the thread title with some sort of 🆕 emoji, but then edit the thread title to remove the emoji as soon as someone who isn't the original author responds.

**Comment by MarcusOtter** [comment]
Crossposting from #25: It would be nice to add ✅ as an emoji when the thread is closed as well (which should be removed if the thread is archived).

An idea that popped into my head as I was writing this: always have one emoji prepended to the threads that indicate the state they're in, such as:
- 🆕 New thread, no replies yet
- 🧵 Active thread
- ✅ Manually closed/archived thread
- ⏲️ Thread timed out without being manually closed

Naturally, they should be configurable 😄

**Comment by FredKSchott** [comment]
Yes! +1 love this idea

**Comment by MarcusOtter** [comment]
The original proposal will be implemented in #34 as well as an option to turn it off. Customized and more emojis will come later!

**Comment by ririko5834** [comment]
> 

Yes there should be more options for emojis

**Comment by MarcusOtter** [comment]
Due to #72 we will keep the title emojis to an absolute minimum until that rate limit issue is solved (which is completely out of our hands) :/
